/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import tinymce from "@sklinet/strapi-plugin-tinymce/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import cookieManager from "strapi-plugin-cookie-manager/strapi-admin";
import metrics from "../../src/plugins/metrics/strapi-admin";
import comments from "../../src/plugins/comments/strapi-admin";
import internallink from "../../src/plugins/internallink/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    tinymce: tinymce,
    "strapi-cloud": strapiCloud,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "cookie-manager": cookieManager,
    metrics: metrics,
    comments: comments,
    internallink: internallink,
  },
});
